blog:
  url: https://stonehee99.tistory.com/
  contents-class-name: index-template
  title-class-name: title
  summary-class-name: desc
  date-class-name: date

github:
  repo-name: stoneHee99/stoneHee99
